server:
  port: 10003

spring:
  application:
    name: service-wechat

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10000/eureka/

logging:
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%.-1level] [%thread] [%logger{1}] %msg%n%throwable{5}'
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%.-1level] [%thread] [%logger{1}] %msg%n%throwable{5}'
  level:
    root: info
    com: error
    org:
      ainy: info
      apache: error
      springframework: error